version: '1.0'

services:
  database:
    image: postgres
    ports:
      - 5431:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_DB=app_db
    volumes:
      - postgres_volume:/var/lib/postgresql/data

volumes:
  postgres_volume: